// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyApp.Infrastructure;

#nullable disable

namespace PharmacyApp.Infrastructure.Migrations
{
    [DbContext(typeof(PharmacyAppContext))]
    [Migration("20251031110206_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.MedicineModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PharmacyModelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyModelId");

                    b.ToTable("Medicines", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.PharmacyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactCustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactCustomerId")
                        .IsUnique();

                    b.ToTable("Pharmacies", (string)null);
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.PrescriptionModel", b =>
                {
                    b.HasBaseType("PharmacyApp.Infrastructure.Models.MedicineModel");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MedicineModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("TEXT");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MedicineModelId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.MedicineModel", b =>
                {
                    b.HasOne("PharmacyApp.Infrastructure.Models.PharmacyModel", null)
                        .WithMany("Medicines")
                        .HasForeignKey("PharmacyModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.PharmacyModel", b =>
                {
                    b.HasOne("PharmacyApp.Infrastructure.Models.CustomerModel", "ContactCustomer")
                        .WithOne("PharmacyContactFor")
                        .HasForeignKey("PharmacyApp.Infrastructure.Models.PharmacyModel", "ContactCustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContactCustomer");
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.PrescriptionModel", b =>
                {
                    b.HasOne("PharmacyApp.Infrastructure.Models.CustomerModel", "Customer")
                        .WithMany("Prescriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmacyApp.Infrastructure.Models.MedicineModel", null)
                        .WithOne()
                        .HasForeignKey("PharmacyApp.Infrastructure.Models.PrescriptionModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Infrastructure.Models.MedicineModel", null)
                        .WithMany("Prescriptions")
                        .HasForeignKey("MedicineModelId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.CustomerModel", b =>
                {
                    b.Navigation("PharmacyContactFor")
                        .IsRequired();

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.MedicineModel", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("PharmacyApp.Infrastructure.Models.PharmacyModel", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
